const mongoose=require('mongoose')
const userSchema= new mongoose.Schema({
    userName:{
        type:String
    },
    Email:{
        type:String
    },
    imageUrl:{
        type:String
    },
    googleId:{
        type:String
    },
    social:{
        type:Array
    },
    about:{
        type:String
    },
    github:{
        type:String
    },
    linkedln:{
        type:String
    },
    twitter:{
        type:String
    },
    leetcode:{
        type:String
    },
    gfg:{
        type:String
    },
    codechef:{
        type:String
    },
    codeforces:{
        type:String
    },
    savepin:{
        type:Array
    },
    backgroundImage:{
        type:String
    },
    rating:{
        type:Array
    }
})
const usermodel=mongoose.model('users',userSchema)
module.exports=usermodel